services:
  whisper-api:
    image: 214882929820.dkr.ecr.us-east-1.amazonaws.com/whisper_ft:v1.0.3
    ports:
      - "8000:8000"
    environment:
      MODEL_NAME: large-v3-turbo
      UVICORN_WORKERS: 2
      beep_detection: OFF
    runtime: nvidia
    networks:
      - whisper_net

networks:
  whisper_net:
    driver: bridge

